export enum PushNotificationNameEnum {
    CREATE_REQUEST_ON_JOIN_EVENT = 'CREATE_REQUEST_ON_JOIN_EVENT',
    NEW_APPLICATION = 'NEW_APPLICATION',
    APPLICATION_APPROVED = 'APPLICATION_APPROVED',
    NEW_EVENT_MEMBER = 'NEW_EVENT_MEMBER',
    APPLIED_MEMBER_BEEN_DECLINED = 'APPLIED_MEMBER_BEEN_DECLINED',
    APPROVED_MEMBER_DECLINED = 'APPROVED_MEMBER_DECLINED',
    APPROVED_MEMBER_DECLINED_FOR_PARTICIPANTS = 'APPROVED_MEMBER_DECLINED_FOR_PARTICIPANTS',
    APPROVED_MEMBER_REFUSE =  'APPROVED_MEMBER_REFUSE',
    APPLICATION_REFUSE = 'APPLICATION_REFUSE',
    EVENT_DETAILS_UPDATE = 'EVENT_DETAILS_UPDATE',
    EVENT_DELETED = 'EVENT_DELETED',
    CUSTOM_NAME = 'CUSTOM_NAME'

}
