export enum PushNotificationNameEnum {
    CREATE_REQUEST_ON_JOIN_EVENT = 'CREATE_REQUEST_ON_JOIN_EVENT',
    USER_APPROVE_ON_EVENT = 'USER_APPROVE_ON_EVENT',
    MEMBER_WITH_STATUS_APPLIED_GET_RENOUNCEMENT = 'MEMBER_WITH_STATUS_APPLIED_GET_RENOUNCEMENT',
    MEMBER_WITH_STATUS_APPROVED_GET_RENOUNCEMENT = 'MEMBER_WITH_STATUS_APPROVED_GET_RENOUNCEMENT',
    MEMBER_WITH_STATUS_APPROVED_RENOUNCEMENT_FROM_EVENT = 'MEMBER_WITH_STATUS_APPROVED_RENOUNCEMENT_FROM_EVENT',
    MEMBER_WITH_STATUS_APPLIED_RENOUNCEMENT_FROM_EVENT = 'MEMBER_WITH_STATUS_APPLIED_RENOUNCEMENT_FROM_EVENT',
    EDIT_EVENT_NOT_DATE = 'EDIT_DATA_EVENT',
    EDIT_DATE_EVENT = 'EDIT_DATE_EVENT',
    EDIT_TIME_EVENT = 'EDIT_TIME_EVENT',
    DELETE_EVENT = 'DELETE_EVENT',
    // CUSTOM
    CUSTOM_NAME = 'CUSTOM_NAME'
}
