export enum EventMembeErrorEnum {
    SELF_EVENT_APPLICATION_ERROR = 'SELF_EVENT_APPLICATION_ERROR',
    APPLICATION__EVENT_TIME_OVERLAP_ERROR = 'APPLICATION__EVENT_TIME_OVERLAP_ERROR',
    CANT_ACCEPT_ALL = 'CANT_ACCEPT_ALL',
    NO_FREE_SPACE = 'NO_FREE_SPACE'
}