export enum EventErrors {
    EVENT_CREATION_TIME_OVERLAP = 'EVENT_CREATION_TIME_OVERLAP',
    EVENT_NOT_FOUND = 'EVENT_NOT_FOUND',
    EVENT_WRONG_TIME = 'EVENT_WRONG_TIME',
    EVENT_START_TIME_LESS_THAN_TODAY = 'EVENT_START_TIME_LESS_THAN_TODAY',
    EVENT_END_TIME_LESS_OR_QUAL_THAN_START_TIME = 'EVENT_END_TIME_LESS_OR_QUAL_THAN_START_TIME',
}